#!/usr/bin/env python3
"""Generate the fixed-width Gen 4 name tables used by the Mode 2 patches."""

import json
import os
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CHAR_TABLE = ROOT / "files" / "CharTable.txt"
JAPANESE_NAMES = ROOT / "texts" / "DP" / "ja" / "monsname.json"
EMERALD_NAMES = Path(os.environ.get("POKEEMERALD", "/private/tmp/pokeemerald")) / "src" / "data" / "text" / "species_names.h"
EMERALD_POKEDEX = Path(os.environ.get("POKEEMERALD", "/private/tmp/pokeemerald")) / "include" / "constants" / "pokedex.h"
OUT_DIR = ROOT / "asm" / "common"
EOS = 0xFFFF
NAME_UNITS = 11


def load_chars():
    result = {}
    for line in CHAR_TABLE.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#") or "\t" not in line:
            continue
        code, char = line.split("\t", 1)
        if len(char) == 1:
            result[char] = int(code, 16)
    return result


def encode(name, chars):
    # The Gen 3 apostrophe glyph converts to Gen 4's typographic apostrophe.
    name = name.replace("'", "’")
    encoded = [chars[c] for c in name]
    if len(encoded) > NAME_UNITS - 1:
        raise ValueError(f"name is too long: {name!r}")
    return encoded + [EOS] + [EOS] * (NAME_UNITS - len(encoded) - 1)


def write_header(path, symbol, names, chars):
    rows = [encode(name, chars) for name in names]
    lines = [
        "/* Generated by scripts/generate_mode2_names.py. */",
        f"static const unsigned short {symbol}[{len(rows)}][{NAME_UNITS}] = {{",
    ]
    for i, row in enumerate(rows):
        values = ", ".join(f"0x{x:04X}" for x in row)
        lines.append(f"    /* {i:3d} */ {{ {values} }},")
    lines.append("};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    chars = load_chars()
    japanese_json = json.loads(JAPANESE_NAMES.read_text(encoding="utf-8"))
    japanese = [entry["translation"] for entry in japanese_json]

    source = EMERALD_NAMES.read_text(encoding="utf-8")
    matches = re.finditer(
        r'^\s*\[SPECIES_([^]]+)\]\s*=\s*_\("([^"]*)"\)', source, re.M
    )
    names_by_species = {}
    for match in matches:
        species, name = match.groups()
        names_by_species[species] = name

    # pokeemerald's species-name table uses internal Gen 3 order: it contains
    # OLD_UNOWN holes and places Chimecho after Deoxys. Build this table from
    # the explicit National Dex enum instead, matching the DS species IDs.
    pokedex_source = EMERALD_POKEDEX.read_text(encoding="utf-8")
    national_enum = pokedex_source.split("// National Pokédex order", 1)[1].split("};", 1)[0]
    national_species = re.findall(r"NATIONAL_DEX_([A-Z0-9_]+)", national_enum)
    english = [names_by_species[species] for species in national_species[:387]]
    if len(english) != 387:
        raise ValueError(f"expected 386 English species names, got {len(english) - 1}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    write_header(OUT_DIR / "mode2_japanese_names.h", "sMode2JapaneseNames", japanese, chars)
    write_header(OUT_DIR / "mode2_english_names.h", "sMode2EnglishNames", english, chars)


if __name__ == "__main__":
    main()
